spring.application.name=gate-way
spring.cloud.gateway.discovery.locator.enabled=true 
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
server.port=8371
jwt.secret=ZmM2Y2U1Y2Y4ZjEwMjkwY2QxjfnfjnfYjU3YjE2MmQ0YjJmMzU2YjY0ZDIzMfjfjfMxYjM3YjU0YjEwMjU=
jwt.expiration=3600000